.PHONY: clean All

All:
	@echo "----------Building project:[ constructor_destructor - Debug ]----------"
	@cd "C:\Users\user\Desktop\College\Cpp_codes\cpp_class\constructor_destructor" && "$(MAKE)" -f  "constructor_destructor.mk"
clean:
	@echo "----------Cleaning project:[ constructor_destructor - Debug ]----------"
	@cd "C:\Users\user\Desktop\College\Cpp_codes\cpp_class\constructor_destructor" && "$(MAKE)" -f  "constructor_destructor.mk" clean
