.PHONY: clean All

All:
	@echo "----------Building project:[ DeepCopy - Debug ]----------"
	@cd "C:\Users\user\Desktop\College\Cpp_codes\cpp_class\DeepCopy" && "$(MAKE)" -f  "DeepCopy.mk"
clean:
	@echo "----------Cleaning project:[ DeepCopy - Debug ]----------"
	@cd "C:\Users\user\Desktop\College\Cpp_codes\cpp_class\DeepCopy" && "$(MAKE)" -f  "DeepCopy.mk" clean
