.PHONY: clean All

All:
	@echo "----------Building project:[ ShallowCopy - Debug ]----------"
	@cd "C:\Users\user\Desktop\College\Cpp_codes\cpp_class\ShallowCopy" && "$(MAKE)" -f  "ShallowCopy.mk"
clean:
	@echo "----------Cleaning project:[ ShallowCopy - Debug ]----------"
	@cd "C:\Users\user\Desktop\College\Cpp_codes\cpp_class\ShallowCopy" && "$(MAKE)" -f  "ShallowCopy.mk" clean
